Import("env")

import csv
import json
import os
import shutil
import subprocess
import sys

if env.IsIntegrationDump():
    Return()

# The compilation database is generated by PlatformIO itself. During the
# nested compiledb call, this script must not start another nested build.
if os.environ.get("FY_MISRA_COMPILEDB") == "1":
    Return()

project_dir = env.subst("$PROJECT_DIR")
cppcheck_dir = os.path.join(project_dir, ".cppcheck")

print("\n🔍 Running MISRA / Cppcheck before build...\n")

reports_dir = os.path.join(project_dir, "reports")
full_report_file = os.path.join(cppcheck_dir, "misra_full.csv")
report_file = os.path.join(reports_dir, "misra.csv")

os.makedirs(reports_dir, exist_ok=True)
os.makedirs(cppcheck_dir, exist_ok=True)

cppcheck = shutil.which("cppcheck")

if cppcheck is None and os.name == "nt":
    windows_cppcheck = r"C:\Program Files\Cppcheck\cppcheck.exe"
    if os.path.isfile(windows_cppcheck):
        cppcheck = windows_cppcheck

if cppcheck is None:
    print("❌ Cppcheck not found. MISRA check aborted.")
    sys.exit(1)

# PlatformIO writes compile_commands.json into the project root.
# Generate a fresh database from the active PlatformIO environment so that
# Cppcheck sees the same defines, include paths and toolchain as the firmware.
pio_result = os.environ.copy()
pio_result["FY_MISRA_COMPILEDB"] = "1"

compiledb_cmd = [
    env.subst("$PYTHONEXE"),
    "-m",
    "platformio",
    "run",
    "-e",
    env.subst("$PIOENV"),
    "-t",
    "compiledb",
]

if subprocess.call(compiledb_cmd, cwd=project_dir, env=pio_result) != 0:
    print("\n❌ Failed to generate PlatformIO compilation database. Build aborted.\n")
    sys.exit(1)

project_compile_db = os.path.join(project_dir, "compile_commands.json")
cppcheck_compile_db = os.path.join(cppcheck_dir, "compile_commands.json")

if not os.path.isfile(project_compile_db):
    print(
        "\n❌ PlatformIO compilation database not found. "
        "MISRA check aborted.\n"
    )
    sys.exit(1)

# Keep the generated database out of the project root and together with the
# Cppcheck cache. Only FY application sources are checked; PlatformIO core
# and third-party libraries are intentionally excluded.
with open(project_compile_db, encoding="utf-8") as source:
    compile_commands = json.load(source)

project_sources = []
for entry in compile_commands:
    file_path = os.path.abspath(entry.get("file", ""))
    relative_path = os.path.relpath(file_path, project_dir)
    if relative_path.startswith(("src\\", "src/", "lib\\", "lib/")):
        project_sources.append(entry)

with open(cppcheck_compile_db, "w", encoding="utf-8") as target:
    json.dump(project_sources, target, indent=2)

os.remove(project_compile_db)

# Third-party code is explicitly excluded from the project MISRA gate.
# Keep the list in a separate, versioned file so exclusions remain visible
# and reviewable.
exclude_file = os.path.join(project_dir, "scripts", "misra_exclude.txt")
suppressions = []

if os.path.isfile(exclude_file):
    with open(exclude_file, encoding="utf-8") as source:
        for line in source:
            pattern = line.strip()
            if pattern and not pattern.startswith("#"):
                suppressions.append("*:" + pattern)

cmd = [
    cppcheck,
    "--enable=warning,style,performance",
    "--addon=misra",
    "--project=.cppcheck/compile_commands.json",
    "--inline-suppr",
    "--template={file},{line},{severity},{id},{message}",
    "--output-file=.cppcheck/misra_full.csv",
    "--cppcheck-build-dir=.cppcheck",
]

for suppression in suppressions:
    cmd.append("--suppress=" + suppression)

result = subprocess.call(cmd, cwd=project_dir)

if result != 0:
    print("\n❌ Cppcheck itself failed. Build aborted.\n")
    sys.exit(1)

misra_findings = 0
error_findings = 0

with open(full_report_file, newline="", encoding="utf-8") as source:
    with open(report_file, "w", newline="", encoding="utf-8") as target:
        writer = csv.writer(target, lineterminator="\n")

        for row in csv.reader(source):
            if len(row) < 5:
                continue

            severity = row[2].strip().lower()
            finding_id = row[3].strip().lower()
            is_misra = finding_id.startswith("misra-c2012-")
            is_config = finding_id == "misra-config"

            if severity == "error" or is_misra:
                writer.writerow(row)

            if is_misra:
                misra_findings += 1
            elif severity == "error" and not is_config:
                error_findings += 1

if misra_findings > 0:
    print(
        f"\n❌ {misra_findings} MISRA issue(s) found. "
        "Build aborted. See reports/misra.csv.\n"
    )
    sys.exit(1)

if error_findings > 0:
    print(
        f"\n❌ {error_findings} error(s) found. "
        "Build aborted. See reports/misra.csv.\n"
    )
    sys.exit(1)

print("\n✅ MISRA / Cppcheck passed. See reports/misra.csv\n")
