Import("env")

import csv
import os
import shutil
import subprocess
import sys

if env.IsIntegrationDump():
    Return()

# The compilation database is generated by PlatformIO itself. During the
# nested compiledb call, this script must not start another nested build.
if os.environ.get("FY_MISRA_COMPILEDB") == "1":
    Return()

# Use PlatformIO's own compilation database with the complete build context.
# Toolchain include paths are added by PlatformIO when the compiledb target runs.
project_dir = env.subst("$PROJECT_DIR")
cppcheck_dir = os.path.join(project_dir, ".cppcheck")
compile_db_file = os.path.join(cppcheck_dir, "compile_commands.json")
env.Replace(COMPILATIONDB_INCLUDE_TOOLCHAIN=True)
env.Replace(COMPILATIONDB_PATH=compile_db_file)

print("\n🔍 Running MISRA / Cppcheck before build...\n")

reports_dir = os.path.join(project_dir, "reports")
full_report_file = os.path.join(cppcheck_dir, "misra_full.csv")
report_file = os.path.join(reports_dir, "misra.csv")

os.makedirs(reports_dir, exist_ok=True)
os.makedirs(cppcheck_dir, exist_ok=True)

cppcheck = shutil.which("cppcheck")

if cppcheck is None and os.name == "nt":
    windows_cppcheck = r"C:\Program Files\Cppcheck\cppcheck.exe"
    if os.path.isfile(windows_cppcheck):
        cppcheck = windows_cppcheck

if cppcheck is None:
    print("❌ Cppcheck not found. MISRA check aborted.")
    sys.exit(1)

# Generate a fresh compilation database from the active PlatformIO
# environment. This keeps defines, include paths and toolchain settings
# aligned with the actual firmware build.
pio_result = os.environ.copy()
pio_result["FY_MISRA_COMPILEDB"] = "1"

compiledb_cmd = [
    env.subst("$PYTHONEXE"),
    "-m",
    "platformio",
    "run",
    "-e",
    env.subst("$PIOENV"),
    "-t",
    "compiledb",
]

if subprocess.call(compiledb_cmd, cwd=project_dir, env=pio_result) != 0:
    print("\n❌ Failed to generate PlatformIO compilation database. Build aborted.\n")
    sys.exit(1)

if not os.path.isfile(compile_db_file):
    print(
        "\n❌ PlatformIO compilation database not found. "
        "MISRA check aborted.\n"
    )
    sys.exit(1)

cmd = [
    cppcheck,
    "--enable=warning,style,performance",
    "--addon=misra",
    "--project=.cppcheck/compile_commands.json",
    "--inline-suppr",
    "--template={file},{line},{severity},{id},{message}",
    "--output-file=.cppcheck/misra_full.csv",
    "--cppcheck-build-dir=.cppcheck",
]

result = subprocess.call(cmd, cwd=project_dir)

if result != 0:
    print("\n❌ Cppcheck itself failed. Build aborted.\n")
    sys.exit(1)

misra_findings = 0
error_findings = 0

with open(full_report_file, newline="", encoding="utf-8") as source:
    with open(report_file, "w", newline="", encoding="utf-8") as target:
        writer = csv.writer(target, lineterminator="\n")

        for row in csv.reader(source):
            if len(row) < 5:
                continue

            severity = row[2].strip().lower()
            finding_id = row[3].strip().lower()
            is_misra = finding_id.startswith("misra-c2012-")
            is_config = finding_id == "misra-config"

            if severity == "error" or is_misra:
                writer.writerow(row)

            if is_misra:
                misra_findings += 1
            elif severity == "error" and not is_config:
                error_findings += 1

if misra_findings > 0:
    print(
        f"\n❌ {misra_findings} MISRA issue(s) found. "
        "Build aborted. See reports/misra.csv.\n"
    )
    sys.exit(1)

if error_findings > 0:
    print(
        f"\n❌ {error_findings} error(s) found. "
        "Build aborted. See reports/misra.csv.\n"
    )
    sys.exit(1)

print("\n✅ MISRA / Cppcheck passed. See reports/misra.csv\n")
