#pragma once
#include "Protokoll.h"

/**
 * @brief References to controller data exchanged through the UART interface.
 */
struct UART_Context_t
{
    FY_SystemStatus_t* systemStatus;
    uint8_t*    uartError;
    int32_t*     motorPosition;
    FY_Track_t*  Track_INFO;
    uint16_t*    motorSpeed;
};
 enum class UART_CommandStatus_t : uint8_t
    {
        VALID,
        CMD_INVALID,
        DATA_INVALID,
        CRC_INVALID
    };

// UART communication speed: 115200 baud, 8 data bits, no parity, 1 stop bit (8N1).
#define UART_BAUD_RATE 115200
// Protokoll time out 

constexpr uint32_t UART_TIMEOUT_BYTES = 5; //  5 Byte warten wir  auf eien fortsetzung des telegramms... 

constexpr uint32_t UART_TIMEOUT_US =
    (UART_TIMEOUT_BYTES * 10UL * 1000000UL) / UART_BAUD_RATE;





/**
 * @brief UART module error flags.
 */

/// @brief No command data is available.
constexpr uint8_t UART_ERROR_NO_CONTENT      = 0x01;
/// @brief No UART connection has been detected.
constexpr uint8_t UART_ERROR_NO_CONNECTION   = 0x02;
/// @brief The received command is unknown.
constexpr uint8_t UART_ERROR_UNKNOWN_COMMAND = 0x04;
/// @brief The command is invalid for the current state.
constexpr uint8_t UART_ERROR_INVALID_STATE   = 0x08;

/** @brief State machine states used while receiving a command. */
enum class ReceiveState : uint8_t
{
    FindCommand,
    ReadData,
    CheckCRC
};


/**
 * @brief Manages UART communication with the controller.
 */
class UART
{
public:
          

    /** @brief Constructs a UART communication handler. */
    UART();

    /**
     * @brief Initializes the handler with controller data.
     * @param context References to the controller state.
     */
    void begin(UART_Context_t& context);

    /** @brief Processes incoming commands and outgoing responses. */
    void update();

///@brief Errorhandling 
 UART_CommandStatus_t getCommandStatus();
  void clearCommandStatus();




private:
    // Internal state.
    
     bool commandReady =false;// Status des telegramms  false → Postfach frei
                              //                       true  → vollständiges Telegramm liegt vor / wird verarbeitet
   uint8_t UART_Error; ///< Error flags generated by the UART handler.

    UART_Context_t* UART_context; ///< Controller data used by the UART handler.
    
    uint8_t commandLength; ///< Length of the currently received command.
    uint8_t expectedLength; ///< Expected length of the current command.
    unsigned long lastByteTime;  // we have to wait not  forever .. 

    /** @brief Stores a decoded command and its validation result. */
    struct CommandBuffer_t
    {
        uint8_t              cmd;
        uint8_t              data[MAX_COMMAND_LENGTH - 1];
        uint8_t              CMD_CRC;
        CommandType          type;
        uint8_t              response;
        UART_CommandStatus_t  status;
    };
        CommandBuffer_t CommandBuffer; ///< Currently buffered command.

    /** @brief Stores a response until it can be transmitted. */
    struct ResponseBuffer_t
    {
        uint8_t  id;
        uint8_t* data;
        uint8_t  length;
        bool     responsePending;
    };
    ResponseBuffer_t ResponseBuffer; ///< Pending response data.

    uint8_t dataIndex; ///< Index of the next byte to be received.
    ReceiveState receiveState = ReceiveState::FindCommand; ///< Current receive state.
    /** @brief Receives data from the UART interface. */
    void receive();

    /** @brief Decodes the received command. */
    void decodeCommand();

    /** @brief Sends a response to the remote device. */
    void sendResponse();
        /** @brief Queues a response for transmission. */
    void setResponse(uint8_t id, uint8_t* data, uint8_t length);

        /** @brief Checks whether a motor error prevents movement commands. */
        bool CheckError();
        /** @brief Checks whether the motor is busy with another operation. */
        bool CheckBusy();
        /** @brief Stores a valid movement command for execution. */
        bool SetCommand();

        /** @brief Checks the received command CRC. */
    bool Check_CRC();
        /** @brief Calculates the CRC for a command or response. */
    uint8_t Calc_CRC(uint8_t id,const uint8_t* data,uint8_t length); 


    /** @brief Sends the UART handshake message. */
    void sendHello();
    /** @brief Decodes immediate commands. */
    void decodeImmediate(); 
    /** @brief Decodes executable movement commands. */
    void decodeExecute();
    /** @brief Decodes priority commands. */
    void decodePriority();





    /** @brief Command handlers for status and diagnostic requests. */
    void handleGetStatus();
    void handleGetError();
    void handleGetPosition();
    void handleGetTrack();
    void handleHelp();

    /** @brief Command handlers for configuration and movement requests. */
    void handleReference();
    void handleSetSpeed();
    void handleGo();
    void handleLeft();
    void handleRight();
    void handleSetPosition();
    void handleSetTrack();
    void handleSetRemote();
    void handleSetLocal();

    /** @brief Handles a stop command and busy-state responses. */
    void handleStop();
    void handle_Busy();
    void handle_ACK();
};