#pragma once

/**
 * @file Firmware.h
 * @brief Central firmware identity information.
 *
 * Release version is maintained manually. Build date/time are generated by
 * the compiler. FW_GIT_COMMIT is injected by PlatformIO from the Git HEAD.
 */

constexpr char FW_NAME[]    = "FY_Controller_Motor";
constexpr char FW_VERSION[] = "1.0.0";
constexpr char FW_BUILD[]   = __DATE__;
constexpr char FW_TIME[]    = __TIME__;

#ifndef FW_GIT_COMMIT
#define FW_GIT_COMMIT "unknown"
#endif
